platform :ios, '9.0'

target '星途' do

  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'DZNEmptyDataSet'
  pod 'SDCycleScrollView'
  pod 'UIView+FDCollapsibleConstraints'
  pod 'TZImagePickerController'
  pod 'FDFullscreenPopGesture'
#  pod 'JXPagingView'
  pod 'JXPagingView/Pager'
  pod 'JXCategoryView'
  pod 'JQFMDB'
  pod 'ZXCountDownView'
  pod 'ZFPlayer', '~> 4.0'
  pod 'ZFPlayer/AVPlayer', '~> 4.0'
  pod 'ZFPlayer/ControlView', '~> 4.0'
  pod 'SocketRocket'
  pod 'UMCommon'
  pod 'YBImageBrowser'
  pod 'XXNibBridge'
  pod 'LBXScan'
  pod 'IQKeyboardManager'
  pod 'AppOrderFiles'
end
